services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/datalog:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    # depends_on:
    #   - zookeeper
    ports:
      - 9096:9096
      - 19096:19096
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_ZOOKEEPER_CONNECT: XXXXXXXX:2181
      KAFKA_LISTENERS: INTERNAL://:19096,EXTERNAL://:9096
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://XXXXXXX:19096,EXTERNAL://XXXXXXXX:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 5
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 5
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 5
      KAFKA_MIN_INSYNC_REPLICAS: 5
      # KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  
  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     KAFKA_BROKERCONNECT: "kafka_1:19092"
  #   depends_on:
  #     - kafka_1
      # - kafka_2
      # - kafka_3